FROM node:22-bookworm-slim AS base
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

FROM base AS deps
COPY package.json ./
RUN npm install

FROM deps AS dev-base
COPY . .

FROM dev-base AS dev
RUN npx playwright install --with-deps chromium
CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0"]

FROM dev-base AS worker
CMD ["npm", "run", "worker:dev"]

FROM deps AS builder
ARG APP_URL
ARG DATABASE_URL
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG OPENAI_API_KEY
ARG OPENAI_GENERATION_MODEL
ARG EMBEDDING_MODEL
ARG EMBEDDING_DIMENSION
ARG DEMO_USER_EMAIL
ARG DEMO_USER_PASSWORD
ARG STORAGE_BACKEND=local
ARG STORAGE_LOCAL_DIR=./data/uploads
ENV APP_URL=$APP_URL
ENV DATABASE_URL=$DATABASE_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV OPENAI_GENERATION_MODEL=$OPENAI_GENERATION_MODEL
ENV EMBEDDING_MODEL=$EMBEDDING_MODEL
ENV EMBEDDING_DIMENSION=$EMBEDDING_DIMENSION
ENV DEMO_USER_EMAIL=$DEMO_USER_EMAIL
ENV DEMO_USER_PASSWORD=$DEMO_USER_PASSWORD
ENV STORAGE_BACKEND=$STORAGE_BACKEND
ENV STORAGE_LOCAL_DIR=$STORAGE_LOCAL_DIR
COPY . .
RUN npm run build

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/src/db/migrations ./src/db/migrations
COPY --from=builder /app/data ./data
EXPOSE 3000
CMD ["node", "server.js"]
